import os
import streamlit as st
from langchain.llms import OpenAI
from dotenv import load_dotenv
from openai_key import another_key  # Ensure this file contains your API key securely

# Load environment variables
load_dotenv()
os.environ['OPENAI_API_KEY'] = another_key  # Set API key for OpenAI

def get_response(question: str) -> str:
    """
    Generate a response from OpenAI's LLM for a given question.
    
    Parameters:
    question (str): The user's input query.

    Returns:
    str: The response generated by the LLM.
    """
    llm = OpenAI(model_name="gpt-3.5-turbo-1106", temperature=0.6)
    return llm(question)

# Initialize Streamlit app
st.set_page_config(page_title="Chatbot Demo", page_icon="💬")
st.title("LLM-Powered Chatbot")

# User input field
user_input = st.text_input("Enter your question:", key="input")
submit = st.button("Get Response")

# Display response when the button is clicked
if submit and user_input:
    response = get_response(user_input)
    st.subheader("Chatbot Response:")
    st.write(response)
